version: 2
jobs:
  build:
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
      pre:
        - sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1

## Customize test commands
test:
  override:
    - lein test-all # run both test (for clj) and doo (for cljs)
